In [135]:
import pandas as pd
from sklearn import model_selection
from sklearn.linear_model import LinearRegression

In [136]:
df = pd.read_csv('training_boston_x_y_train.csv')
df

# CRIM        ZN     INDUS      CHAS       NOX        RM       AGE  \
0   -0.407850 -0.487722 -1.266023 -0.272599 -0.576134  1.239974  0.840122   
1   -0.407374 -0.487722  0.247057 -0.272599 -1.016689  0.001946 -0.838337   
2    0.125179 -0.487722  1.015999 -0.272599  1.367490 -0.439699  0.687212   
3    0.028304 -0.487722  1.015999 -0.272599  1.859875 -0.047918  0.801005   
4   -0.412408 -0.487722 -0.969827 -0.272599 -0.913029 -0.384137 -0.834781   
5   -0.416934  1.014463 -1.403178 -0.272599 -0.973497  1.362495 -0.685427   
6   -0.002920 -0.487722  1.015999 -0.272599  0.218592  0.217069  0.228480   
7   -0.225559 -0.487722  1.231945 -0.272599  2.732346 -0.231698  1.021481   
8   -0.395561  0.456508 -0.769931 -0.272599 -1.068519 -0.083534  0.377835   
9   -0.413779  2.945843 -1.403178 -0.272599 -1.301754  1.428029 -1.225947   
10  -0.397305 -0.487722 -0.548149 -0.272599 -0.532942  0.130165 -0.507624   
11  -0.406627 -0.487722  0.247057 -0.272599 -1.016689 -0.008027  0.210700   
12  -0.347243  0.370669 -1.045700 -0.272599  0.797361  3.446770  0.651651   
13  -0.077985 -0.487722  1.231945 -0.272599  0.434551 -0.261616  0.868570   
14   0.259352 -0.487722  1.015999 -0.272599  1.367490  0.325343  0.758333   
15   0.141864 -0.487722  1.015999 -0.272599  1.367490  0.593179  0.761889   
16  -0.393160 -0.487722 -0.079780  3.668398 -0.567496 -0.680466 -0.525404   
17  -0.345121 -0.487722 -0.437258 -0.272599 -0.144217 -0.478164 -0.240919   
18  -0.328444 -0.487722 -0.437258 -0.272599 -0.144217  0.299699  0.918355   
19  -0.409267  2.945843 -0.902709 -0.272599 -1.241285  1.230001 -1.453535   
20  -0.295732 -0.487722 -0.437258 -0.272599 -0.144217 -0.498110 -1.396638   
21  -0.415272 -0.487722 -0.593381 -0.272599 -0.740262  1.282714 -0.265812   
22  -0.411315  1.229060 -0.689681  3.668398 -0.930305  0.771261 -1.457091   
23  -0.414974 -0.487722 -1.306878 -0.272599 -0.835284  0.207096 -0.351157   
24  -0.006841 -0.487722  1.231945  3.668398  2.732346 -0.188959  0.498741   
25  -0.344167 -0.487722 -0.437258 -0.272599 -0.144217 -0.268740  0.566306   
26   0.443643 -0.487722  1.015999 -0.272599  0.365444 -0.951151  1.042817   
27  -0.358853 -0.487722 -0.720322 -0.272599 -0.412006  1.529180  0.107574   
28  -0.403610 -0.487722 -0.616727 -0.272599 -0.921667  0.691480 -2.335437   
29  -0.414438  3.053142 -1.328764 -0.272599 -1.206732 -0.174712 -1.073037   
..        ...       ...       ...       ...       ...       ...       ...   
349  1.072221 -0.487722  1.015999 -0.272599  1.600725 -0.613507  0.996589   
350 -0.410416 -0.487722  2.117615 -0.272599  0.227231 -0.590712  0.040009   
351 -0.390607 -0.487722 -0.211099 -0.272599  0.261784 -0.378438 -0.116457   
352 -0.409192  2.087452 -1.378373 -0.272599 -1.241285  0.419371 -1.161938   
353 -0.412276 -0.487722 -1.127409 -0.272599 -0.567496  1.131700 -0.194691   
354 -0.340214 -0.487722 -0.437258 -0.272599 -0.144217 -0.671918  0.772557   
355  4.908122 -0.487722  1.015999 -0.272599  1.194724 -2.515426  1.117494   
356 -0.157354 -0.487722  1.231945 -0.272599  0.434551 -0.613507  0.825898   
357 -0.270170 -0.487722  1.231945  3.668398  0.434551 -0.049342  0.854346   
358 -0.230656 -0.487722 -0.437258 -0.272599 -0.144217 -0.268740  1.007257   
359  0.174238 -0.487722  1.015999 -0.272599  1.367490  0.017617  0.825898   
360 -0.398769 -0.487722  2.117615 -0.272599  0.227231 -0.425452  0.704992   
361 -0.412132 -0.487722 -1.034027 -0.272599 -0.386091  0.043261  0.171583   
362 -0.416161  2.945843 -1.368160 -0.272599 -1.465882 -0.077835 -1.318405   
363 -0.248059 -0.487722  1.231945 -0.272599  0.434551  1.715810  0.790337   
364 -0.286780 -0.487722 -0.437258 -0.272599 -0.144217 -0.814384  0.907687   
365 -0.371639 -0.487722 -0.180458 -0.272599 -0.092387  0.138713 -0.048892   
366 -0.383616  0.370669 -0.609431 -0.272599 -0.783454 -0.610658 -0.941463   
367  0.725375 -0.487722  1.015999 -0.272599  1.004680  0.725672  1.074822   
368  1.361650 -0.487722  1.015999 -0.272599  1.004680  0.519097  0.879239   
369

In [137]:
Y_train = df[' Y']
Y_train = Y_train.values
Y_train

array([37.9, 21.4, 12.7, 19.9, 22.5, 32.7, 23.2, 21.5, 20.5, 33.3, 23.1,
       20. , 50. , 25. , 20.2, 16.4, 22.4, 20.4, 18.4, 37.3, 23.1, 34.7,
       33.1, 28.7, 15.6, 18.2, 17.2, 31.5, 26.6, 24.1, 22.3, 19.5, 36.1,
       17.6, 33.4,  8.8,  9.7, 13.4, 39.8, 24.4, 17.8, 24.3, 24. , 23.1,
       13.1, 16.7, 22.8, 27.5, 14.6, 13.4, 11. , 19.4, 15. , 44.8, 29.6,
       12.3, 24.6, 10.9, 28. , 30.8, 15.4, 18. , 35.2, 11.5, 19.5, 24.8,
       22.2, 20.1, 15.2, 50. , 17.1, 23. , 12. , 22. , 20. , 20.3, 17.2,
       37.2,  5. , 24.5, 18.9, 24.5, 24.8, 21.6,  7. , 17.7, 12.8, 14.9,
       18.3, 15.6, 19.9, 22.2, 16.7, 32.5, 25.1, 30.1, 16.1, 20.7, 46. ,
       22.3, 23. , 11.9, 23.3, 23.2, 22. , 10.5, 17.2, 29.8, 29. , 17.3,
       20.6, 20.1, 20.6, 17.8, 25. , 22.6, 18.7, 11.3,  9.6, 17.8, 23.9,
       38.7, 21.2, 25. , 28.5, 24. , 20.6,  5. , 22.9, 18.4, 31. , 36. ,
       20.8, 13.3, 23.2, 28.2, 43.8, 26.6, 23.9, 23.9, 27.9, 19.1, 30.5,
        8.3,  8.5, 16.5, 23.8, 19.6, 22.2, 24.3, 32

In [138]:
del df[' Y']

In [139]:
X_train = df.values
X_train

array([[-0.40784991, -0.48772236, -1.2660231 , ..., -0.30309415,
         0.41057102, -1.09799011],
       [-0.40737368, -0.48772236,  0.24705682, ...,  0.1130321 ,
         0.29116915, -0.52047412],
       [ 0.1251786 , -0.48772236,  1.01599907, ...,  0.80657583,
        -3.79579542,  0.89107588],
       ...,
       [-0.40831101, -0.48772236,  0.24705682, ...,  0.1130321 ,
         0.33206621, -0.33404299],
       [-0.41061997, -0.48772236, -1.15221381, ..., -0.71922039,
         0.203235  , -0.74475218],
       [ 0.34290895, -0.48772236,  1.01599907, ...,  0.80657583,
         0.38787479, -1.35871335]])

In [133]:
#X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X_train, Y_train, random_state = 0)

In [140]:
df = pd.read_csv('test_boston_x_test.csv')
X_test = df.values
X_test

array([[-0.40339151, -0.48772236,  0.40609801, ..., -1.13534664,
         0.44105193, -0.89473812],
       [-0.4131781 , -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.50084979],
       [-0.41264948,  0.41358857, -0.80203138, ..., -0.76545664,
         0.44105193, -0.59196275],
       ...,
       [-0.41001449,  2.08745172, -1.37837329, ..., -0.0719129 ,
         0.39094481, -0.68167397],
       [-0.40317611, -0.48772236, -0.37597609, ...,  1.13022958,
         0.34007019,  0.20142086],
       [-0.13356344, -0.48772236,  1.2319449 , ..., -1.73641788,
        -2.93893082,  0.48877712]])

In [141]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(2, interaction_only=True)

X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.fit_transform(X_test)

In [142]:
from sklearn.linear_model import LinearRegression
alg1 = LinearRegression(normalize = True)
alg1.fit(X_train_poly, Y_train)

train_score = alg1.score(X_train_poly, Y_train)
#test_score = alg1.score(X_test_poly, Y_test)
print("Train Score: ", train_score)
#print("Test Score: ", test_score)

Train Score:  0.9245044201476822


In [144]:
Y_pred = alg1.predict(X_test_poly)
np.savetxt("pred_GD.csv", Y_pred, delimiter=",", fmt='%f')

In [125]:
from sklearn import preprocessing
scaler = preprocessing.StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

alg2 = LinearRegression()
alg2.fit(X_train_scaled, Y_train)

train_score = alg2.score(X_train_scaled, Y_train)
test_score = alg2.score(X_test_scaled, Y_test)
print("Train Score: ", train_score)
print("Test Score: ", test_score)

Train Score:  0.7452279192438824
Test Score:  0.6868496456681703


In [120]:
X_train

array([[-0.40262885, -0.48772236, -0.07978012, ...,  0.06679585,
         0.27022723,  0.28131992],
       [-0.27269369, -0.48772236, -0.43725801, ...,  1.17646583,
         0.21814653,  1.17282518],
       [ 0.14876655, -0.48772236,  1.01599907, ...,  0.80657583,
         0.43348653,  0.84481853],
       ...,
       [ 0.65126626, -0.48772236,  1.01599907, ...,  0.80657583,
         0.44105193,  1.53447354],
       [-0.40113961, -0.48772236, -0.37597609, ...,  1.13022958,
         0.41758821, -0.45319071],
       [-0.40726656,  1.22906036, -0.68968118, ..., -0.39556665,
         0.44105193, -1.35590987]])

In [108]:
X_test

array([[-0.20882877, -0.48772236,  1.2319449 , ..., -1.73641788,
        -1.41510429, -0.07191802],
       [ 0.08791388, -0.48772236,  1.01599907, ...,  0.80657583,
         0.44105193,  0.50980319],
       [-0.40609287,  0.79986468, -0.90562701, ..., -0.85792914,
         0.4160532 , -0.03547283],
       ...,
       [ 0.84306011, -0.48772236,  1.01599907, ...,  0.80657583,
        -3.67420069,  1.84145413],
       [-0.30716158, -0.48772236, -0.43725801, ...,  1.17646583,
        -0.55144179,  0.64857523],
       [ 0.88104209, -0.48772236,  1.01599907, ...,  0.80657583,
        -2.70626713,  1.48821619]])

In [28]:
# df = pd.read_csv('test_boston_x_test.csv')
# X_test = df.values
# X_test

array([[-0.40339151, -0.48772236,  0.40609801, ..., -1.13534664,
         0.44105193, -0.89473812],
       [-0.4131781 , -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.50084979],
       [-0.41264948,  0.41358857, -0.80203138, ..., -0.76545664,
         0.44105193, -0.59196275],
       ...,
       [-0.41001449,  2.08745172, -1.37837329, ..., -0.0719129 ,
         0.39094481, -0.68167397],
       [-0.40317611, -0.48772236, -0.37597609, ...,  1.13022958,
         0.34007019,  0.20142086],
       [-0.13356344, -0.48772236,  1.2319449 , ..., -1.73641788,
        -2.93893082,  0.48877712]])

In [34]:
# import numpy as np
# from sklearn.preprocessing import PolynomialFeatures
# poly = PolynomialFeatures(2)

# X_train_poly = poly.fit_transform(X_train)
# X_test_poly = poly.fit_transform(X_test)

In [35]:
# alg = LinearRegression()
# alg.fit(X_train_poly, Y_train)
# Y_pred = alg.predict(X_test_poly)

In [36]:
# type(Y_pred)

numpy.ndarray

In [38]:
# np.savetxt("pred_GD.csv", Y_pred, delimiter=",", fmt='%f')